Repository AlvaroIsrael/gobarber-app, pull requests merged in 2021-07, with the labels that each got.

#144 chore: Added missing migrations info to README.md.
  README.md
  gobarber-backend/README.md
Labels: documentation

#145 chore: Updated contributing section from README.md.
  README.md
  gobarber-backend/README.md
Labels: documentation

#147 chore(👔): Upgrade react version to solve security bot warning.
  gobarber-mobile/android/settings.gradle
  gobarber-mobile/ios/Podfile
  gobarber-mobile/ios/Podfile.lock
  gobarber-mobile/ios/gobarber.xcodeproj/project.pbxproj
  gobarber-mobile/ios/gobarber.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  gobarber-mobile/ios/gobarber.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  gobarber-mobile/ios/gobarber.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  gobarber-mobile/ios/gobarber/Info.plist
  gobarber-mobile/package.json
Labels: enhancement

#149 fix(🐛): Fixed amazon s3 public img path.
  gobarber-backend/src/modules/users/infra/typeorm/entities/User.ts
Labels: bug

#152 feat(👑): Added switch avatar functionality to mobile profile page.
  gobarber-mobile/android/app/src/main/AndroidManifest.xml
  gobarber-mobile/android/build.gradle
  gobarber-mobile/android/gradle.properties
  gobarber-mobile/ios/Podfile.lock
  gobarber-mobile/package.json
  gobarber-mobile/src/pages/Dashboard/styles.ts
  gobarber-mobile/src/pages/Profile/index.tsx
  gobarber-mobile/src/pages/Profile/styles.ts
  gobarber-mobile/src/pages/SignUp/index.tsx
Labels: enhancement

#154 docs(📝): Fixed avatar_url for s3 path in swagger.
  gobarber-backend/swagger.yaml
Labels: documentation

#155 docs: update README.md
  README.md
Labels: documentation

#156 fix(🐛): Updated App logo from svg to png to avoid missing font error.
  README.md
  gobarber-frontend/src/assets/gobarberdarklogo.png
  gobarber-frontend/src/assets/gobarberdarklogo.svg
  gobarber-frontend/src/assets/gobarberlogo.svg
Labels: documentation, enhancement
